### ISSUE TITLE
Does not alert that iTerm needs to be granted access to contacts

### ISSUE THREAD

**Issue by patrickwelker** [olfuerniss/byrthdays#1]
UPDATE: Edited issue title to reflects actual cause of the problem.

Hello old friend, I just installed your latest nifty toy and tried to run `byrthdays -d -1`… but nothing. 

Do I need to be on HighSierra to have byrthdays work?

**Comment by olfuerniss** [comment]
Hi Patrick, the macOS deployment target is set to 10.11 (El Capitan). Do you get an error message? Did you allowed it to access your contacts?

**Comment by patrickwelker** [comment]
I've updated to the latest macOS version in the meantime.

But… I still can't get the binary to work. There is zero output and I don't get asked for access to my contacts. The only time I see anything in stdout is when I use `byrthdays -h`. (-̩__-̩)

I haven't tried compiling it myself yet.

**Comment by olfuerniss** [comment]
It seems to be an access problem. Just removed the access for iTerm and it does not display any contacts. Maybe I should add a warning ... 

Please give your used "terminal App" (like iTerm) access to your contacts. 
1. open macOS System Preferences -> Security & Privacy
2. Switch to the "Privacy" tab
3. Select "Contacts" on the left side
4. Allow iTerm to access your contacts
=> Restart iTerm and try it again

**Comment by patrickwelker** [comment]
That's it. Solved.

I waited for something like this: 

![](https://patrickwelker.com/s/macos-privacy-for-scripts-and-binaries.png)
